[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@solmate/tokens=lib/solmate/src/tokens"]
[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
local = "http://127.0.0.1:8545"
[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
